apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: laravel-prod
  labels:
    app.kubernetes.io/name: laravel-app
    app.kubernetes.io/managed-by: kustomize
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  LOG_CHANNEL: "stderr"
  APP_URL: "http://localhost"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
