apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: laravel-prod
  labels:
    app.kubernetes.io/name: laravel-app
    app.kubernetes.io/managed-by: kustomize
type: Opaque
data:
  APP_KEY: REPLACE_WITH_BASE64_ENCODED_APP_KEY
