apiVersion: v1
kind: Service
metadata:
  name: laravel-app
  namespace: laravel-prod
  labels:
    app.kubernetes.io/name: laravel-app
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app: laravel-app
  ports:
    - name: fpm
      protocol: TCP
      port: 9000
      targetPort: 9000
